name: flutter_application_1
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0" # Asegúrate de que esta línea sea compatible con tu SDK

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  assets:
    - assets/image.png
    - assets/tlf.webp
    - assets/ig.webp
    - assets/mens.webp
    - assets/was.webp
    - assets/add.webp
    - assets/arquitectura.webp
    - assets/pilotando.webp
    - assets/praga.webp
    - assets/retratos.webp
    - assets/avatar.webp
    - assets/ciudad1.webp
    - assets/fruta.webp
    - assets/sandia.webp
    - assets/zumo.webp
    - assets/coco.webp
    - assets/pmiento.webp



  uses-material-design: true
